name: Build on branch push
permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.Qconn.ModbusTcp/**'
      - 'Frends.Qconn.ModbusTcp.Tests/**'
      - 'Frends.Qconn.ModbusTcp.sln'
      - '.github/workflows/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'SECURITY.md'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.Qconn.ModbusTcp
      dotnet_version: 8.0.x
      strict_analyzers: false
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
