name: Build on main
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.Qconn.ModbusTcp/**'
      - 'Frends.Qconn.ModbusTcp.Tests/**'
      - 'Frends.Qconn.ModbusTcp.sln'
      - '.github/workflows/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'SECURITY.md'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/Public_build.yml
    with:
      dotnet_version: 8.0.x
      publish_test_feed: false
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
